"use client";

import { useActionState, useState } from "react";
import type { InvestorPlatformData } from "@/lib/investor-platform";
import {
  deleteDevelopment,
  deleteHolding,
  deleteInsightArticle,
  deleteInvestorProfile,
  deleteSiteUpdate,
  saveDevelopment,
  saveHolding,
  saveInsightArticle,
  saveInvestorProfile,
  saveSiteUpdate,
  type InvestorAdminState,
} from "@/app/admin/actions";

type Tab = "investors" | "developments" | "updates" | "insights";
const input = "w-full border border-border bg-background px-3 py-3 text-sm outline-none focus:border-accent";
const label = "flex flex-col gap-2 text-[10px] tracking-[.14em] uppercase text-muted";

function Result({ state }: { state: InvestorAdminState }) {
  return <>{state.error && <p role="alert" className="text-sm text-clay">{state.error}</p>}{state.success && <p role="status" className="text-sm text-sage">{state.success}</p>}</>;
}

function Submit({ pending, children = "Save" }: { pending: boolean; children?: React.ReactNode }) {
  return <button disabled={pending} className="bg-ink px-5 py-3 text-xs tracking-[.15em] uppercase text-ink-foreground disabled:opacity-50">{pending ? "Saving…" : children}</button>;
}

export function InvestorAdminPlatform({ data }: { data: InvestorPlatformData }) {
  const [tab, setTab] = useState<Tab>("investors");
  const [profileState, profileAction, profilePending] = useActionState(saveInvestorProfile, {});
  const [holdingState, holdingAction, holdingPending] = useActionState(saveHolding, {});
  const [developmentState, developmentAction, developmentPending] = useActionState(saveDevelopment, {});
  const [updateState, updateAction, updatePending] = useActionState(saveSiteUpdate, {});
  const [articleState, articleAction, articlePending] = useActionState(saveInsightArticle, {});
  const tabs: Array<[Tab, string, number]> = [
    ["investors", "Investors & holdings", data.users.length],
    ["developments", "Properties", data.developments.length],
    ["updates", "Site updates", data.updates.length],
    ["insights", "Insights & analysis", data.articles.length],
  ];
  return <section className="border border-border bg-background">
    <header className="border-b border-border p-6 sm:p-8"><p className="text-xs tracking-[.2em] uppercase text-accent">Investor platform</p><h2 className="mt-3 text-3xl font-medium">Portfolio administration.</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-muted">Create investor profiles, assign property holdings, manage developments and publish project communications from one workspace.</p></header>
    <nav className="flex overflow-x-auto border-b border-border" aria-label="Investor administration sections">{tabs.map(([id, name, count]) => <button key={id} onClick={() => setTab(id)} className={`min-w-max border-r border-border px-5 py-4 text-xs tracking-wider ${tab === id ? "bg-ink text-ink-foreground" : "hover:bg-surface"}`}>{name} <span className="ml-2 opacity-60">{count}</span></button>)}</nav>
    <div className="p-5 sm:p-8">
      {tab === "investors" && <div className="grid gap-10 xl:grid-cols-[1.2fr_.8fr]">
        <div><h3 className="text-xs tracking-[.16em] uppercase text-muted">Investor profiles</h3><div className="mt-4 space-y-3">{data.users.map((user) => { const portfolio = data.portfolios.find((item) => item.id === user.portfolioId); return <article key={user.id} className="border border-border p-5"><div className="flex items-start justify-between gap-4"><div><h4 className="font-medium">{user.displayName}</h4><p className="mt-1 text-sm text-muted">{user.accountName} · {user.email}</p></div><form action={deleteInvestorProfile}><input type="hidden" name="id" value={user.id}/><button className="text-[10px] uppercase tracking-wider text-clay">Remove</button></form></div><div className="mt-5 grid grid-cols-2 gap-4 border-t border-border pt-4 text-xs"><span><b className="block text-lg">{portfolio?.value}</b>Portfolio value</span><span><b className="block text-lg">{portfolio?.holdings.length ?? 0}</b>Holdings</span></div>{portfolio && portfolio.holdings.length > 0 && <div className="mt-4 space-y-2">{portfolio.holdings.map((holding) => <div key={holding.developmentId} className="flex items-center justify-between bg-surface px-3 py-2 text-xs"><span>{data.developments.find((item) => item.id === holding.developmentId)?.name} · {holding.currentValue}</span><form action={deleteHolding}><input type="hidden" name="portfolioId" value={portfolio.id}/><input type="hidden" name="developmentId" value={holding.developmentId}/><button className="text-clay">Remove</button></form></div>)}</div>}</article>; })}</div></div>
        <div className="space-y-8"><form action={profileAction} className="space-y-4 border border-border bg-surface p-5"><h3 className="text-sm font-medium">Add investor profile</h3><label className={label}>Login email<input className={input} name="email" required/></label><label className={label}>Display name<input className={input} name="displayName" required/></label><label className={label}>Account / entity<input className={input} name="accountName" required/></label><div className="flex items-center justify-between gap-3"><Result state={profileState}/><Submit pending={profilePending}>Add investor</Submit></div></form>
        <form action={holdingAction} className="space-y-4 border border-border bg-surface p-5"><h3 className="text-sm font-medium">Assign or update holding</h3><label className={label}>Investor<select className={input} name="portfolioId" required>{data.users.map((user) => <option key={user.id} value={user.portfolioId}>{user.displayName} — {user.accountName}</option>)}</select></label><label className={label}>Property<select className={input} name="developmentId" required>{data.developments.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><div className="grid grid-cols-2 gap-3"><label className={label}>Invested<input className={input} name="invested" placeholder="£1.20m" required/></label><label className={label}>Current value<input className={input} name="currentValue" placeholder="£1.62m"/></label><label className={label}>Forecast IRR<input className={input} name="forecastIrr" placeholder="19.2%"/></label><label className={label}>Multiple<input className={input} name="multiple" placeholder="1.35x"/></label></div><div className="flex items-center justify-between gap-3"><Result state={holdingState}/><Submit pending={holdingPending}>Save holding</Submit></div></form></div>
      </div>}
      {tab === "developments" && <div className="grid gap-10 xl:grid-cols-[1.2fr_.8fr]"><div className="space-y-3">{data.developments.map((item) => <article key={item.id} className="flex items-center justify-between border border-border p-5"><div><h3 className="font-medium">{item.name}</h3><p className="mt-1 text-xs text-muted">{item.place} · {item.phase} · {item.progress}% · {item.value}</p></div><form action={deleteDevelopment}><input type="hidden" name="id" value={item.id}/><button className="text-[10px] uppercase tracking-wider text-clay">Remove</button></form></article>)}</div><form action={developmentAction} className="space-y-4 border border-border bg-surface p-5"><h3 className="text-sm font-medium">Add property development</h3><label className={label}>Property name<input className={input} name="name" required/></label><label className={label}>Location<input className={input} name="place" required/></label><div className="grid grid-cols-2 gap-3"><label className={label}>Status<input className={input} name="status" placeholder="On programme"/></label><label className={label}>Phase<input className={input} name="phase" placeholder="Construction"/></label><label className={label}>Progress %<input className={input} name="progress" type="number" min="0" max="100"/></label><label className={label}>Gross value<input className={input} name="value" placeholder="£12.5m"/></label><label className={label}>Map X %<input className={input} name="x" type="number" min="0" max="100"/></label><label className={label}>Map Y %<input className={input} name="y" type="number" min="0" max="100"/></label></div><label className={label}>Next report<input className={input} name="nextReport" placeholder="30 Sep 2026"/></label><div className="flex items-center justify-between gap-3"><Result state={developmentState}/><Submit pending={developmentPending}>Add property</Submit></div></form></div>}
      {tab === "updates" && <div className="grid gap-10 xl:grid-cols-[1.2fr_.8fr]"><div className="space-y-3">{data.updates.map((item) => <article key={item.id} className="border border-border p-5"><div className="flex justify-between gap-4"><div><p className="text-[10px] uppercase tracking-wider text-accent">{item.date} · {item.tag}</p><h3 className="mt-2 font-medium">{item.title}</h3><p className="mt-2 text-sm leading-6 text-muted">{item.body}</p></div><form action={deleteSiteUpdate}><input type="hidden" name="id" value={item.id}/><button className="text-[10px] uppercase tracking-wider text-clay">Remove</button></form></div></article>)}</div><form action={updateAction} className="space-y-4 border border-border bg-surface p-5"><h3 className="text-sm font-medium">Publish site update</h3><label className={label}>Property<select className={input} name="developmentId">{data.developments.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><div className="grid grid-cols-2 gap-3"><label className={label}>Date<input className={input} name="date" placeholder="11 Aug 2026" required/></label><label className={label}>Category<input className={input} name="tag" placeholder="Construction"/></label></div><label className={label}>Title<input className={input} name="title" required/></label><label className={label}>Update<textarea className={`${input} min-h-32`} name="body" required/></label><div className="flex items-center justify-between gap-3"><Result state={updateState}/><Submit pending={updatePending}>Publish update</Submit></div></form></div>}
      {tab === "insights" && <div className="grid gap-10 xl:grid-cols-[1.1fr_.9fr]"><div className="space-y-3">{data.articles.map((item) => <article key={item.id} className="border border-border p-5"><div className="flex justify-between gap-4"><div><p className="text-[10px] uppercase tracking-wider text-accent">{item.category} · {item.date}</p><h3 className="mt-2 font-medium">{item.title}</h3><p className="mt-2 text-sm leading-6 text-muted">{item.summary}</p></div><form action={deleteInsightArticle}><input type="hidden" name="id" value={item.id}/><button className="text-[10px] uppercase tracking-wider text-clay">Remove</button></form></div></article>)}</div><form action={articleAction} className="space-y-4 border border-border bg-surface p-5"><h3 className="text-sm font-medium">Publish insight or analysis</h3><div className="grid grid-cols-2 gap-3"><label className={label}>Category<input className={input} name="category" placeholder="Research"/></label><label className={label}>Date<input className={input} name="date" placeholder="11 Aug 2026"/></label><label className={label}>Read time<input className={input} name="readTime" placeholder="6 min"/></label></div><label className={label}>Title<input className={input} name="title" required/></label><label className={label}>Summary<textarea className={`${input} min-h-24`} name="summary" required/></label><label className={label}>Article body <span className="normal-case tracking-normal">Separate paragraphs with a blank line.</span><textarea className={`${input} min-h-64`} name="body" required/></label><div className="flex items-center justify-between gap-3"><Result state={articleState}/><Submit pending={articlePending}>Publish insight</Submit></div></form></div>}
    </div>
  </section>;
}
