// Deck 02 — The newsletter studio
import { C, MX, CW } from "../theme.mjs";

export const deck = {
  no: 2,
  file: "02-the-newsletter-studio.pptx",
  name: "The newsletter studio",
  title: "The newsletter studio.",
  subtitle: "Writing and publishing news stories that appear on the public News page the moment you press Publish.",
  cover: "cover-news.jpg",
  coverNotes:
    "This session covers the newsletter studio end to end: writing a story, the two formatting tricks, publishing, checking your work, and fixing mistakes. It takes 10–15 minutes to publish a typical story once you've done it twice.",
  slides: [
    {
      type: "agenda",
      title: "What this session covers.",
      sub: "Everything about news stories — the site calls them “issues”. You need to be signed in to the admin area, and a story to tell.",
      items: [
        { title: "Where stories appear", sub: "The public News page, and each story's own page." },
        { title: "The studio tour", sub: "One form, four boxes, and the published-issues list." },
        { title: "Formatting", sub: "Plain typing, plus two optional tricks." },
        { title: "Publish and check", sub: "It goes live immediately — and how to verify." },
        { title: "Fixing mistakes", sub: "The overwrite guard, and the three correction routes." },
        { title: "Signups & the live list", sub: "The subscribe box, and the new subscriber list in the admin." },
      ],
      notes: "Set expectations: publishing is genuinely a 10-minute job. The only rule that matters is at step 4 — publishing is immediate and public, so agree the text before it goes in the box.",
    },
    {
      type: "imageFocus",
      label: "Where stories appear",
      title: "Every story lands on the public News page.",
      textW: 4.3,
      image: "news-public.png",
      imageH: 5.0,
      caption: "The “What we've been up to” list on /news — newest first, immediately after publishing.",
      body: [
        { text: "Stories appear in the archive list on the News page the moment they are published — newest at the top — and each story gets its own page and web address, like /news/2026-08-19-your-headline.", size: 11 },
        { text: "Stories are also picked up by search engines: regular, dated news is the simplest ranking signal the site can send.", size: 11 },
      ],
      panel: {
        tone: "tip",
        title: "One list, two purposes",
        body: "The same page doubles as the public archive and your quickest way to re-read a live story exactly as visitors see it.",
        y: 5.35, h: 1.4,
      },
      notes: "Show the live /news page in the browser if presenting with a connection. Mention the story address format — the title becomes the web address, which is why short factual titles work best.",
    },
    {
      type: "steps",
      label: "The studio tour",
      title: "One form, four boxes, one button.",
      intro: "From the control room, click the Newsletter card. The numbers below match the numbers on the screen.",
      image: "newsletter-studio.png",
      imageW: 5.15,
      caption: "The newsletter studio at /admin/newsletter.",
      steps: [
        { n: 1, title: "Title", body: "The headline — short and factual. It becomes the story's web address too." },
        { n: 2, title: "Date", body: "Today is pre-filled; click to pick another day if you are backdating." },
        { n: 3, title: "Summary", body: "One plain sentence shown under the headline in the news list. The story in fifteen words." },
        { n: 4, title: "Body", body: "The story itself, in normal paragraphs — press Enter twice between them." },
        { n: 5, title: "Publish issue", body: "The story goes live the moment you click this." },
        { n: 6, title: "Published issues", body: "Everything already live, newest first. Click any title to read it as visitors do." },
      ],
      bodySize: 10,
      notes: "Walk the six numbered markers on the screenshot in order. All four boxes must be filled before Publish will work — the form tells you if one is missing.",
    },
    {
      type: "panels",
      label: "Formatting",
      title: "Plain typing, plus two optional tricks.",
      intro: "There is no bold/italic toolbar — the site styles every story for you, so every story matches the house look.",
      cols: 3,
      panels: [
        { tone: "plain", title: "Paragraphs", body: ["Press Enter twice — one empty line — between paragraphs. Miss the empty line and they run together into one block."] },
        { tone: "plain", title: "Section headings", body: ["Start a line with ## and a space:", "## What happens next", "…becomes a bold sub-heading."] },
        { tone: "plain", title: "Bullet lists", body: ["Start each line with a dash and a space:", "- Planning approved in May", "Consecutive dash lines become one list."] },
      ],
      panelH: 2.5,
      notes: "Live demo moment: type a heading and a two-item list in the body box, publish to a test story later or just show the hint text under the box. Reassure: everything else is just normal typing.",
    },
    {
      type: "steps",
      label: "Publish",
      title: "Publish, then check your work on the live page.",
      image: "news-story.png",
      imageW: 5.15,
      caption: "A published story as visitors read it.",
      steps: [
        { n: 1, title: "Click Publish issue", body: "Two confirmations: a message under the form — “Issue published.” with a link — and the story at the top of the Published issues list." },
        { n: 2, title: "Open the confirmation link", body: "Read the live story. Check the headline, the date, and skim the text — typos are far easier to spot on the finished page than in the typing box." },
        { n: 3, title: "Glance at the News page", body: "Your story should be at the top of the archive list." },
      ],
      panel: {
        tone: "warn",
        title: "Publishing is immediate and public",
        body: "There is no draft mode. Want a second pair of eyes? Agree the text in an email or document first, then paste it in and publish.",
        h: 1.15,
      },
      notes: "The warning is the one thing to land on this slide. The workflow for review is deliberately outside the studio: agree the words first, then publish once.",
    },
    {
      type: "steps",
      label: "Corrections",
      title: "Fixing a mistake in a published story.",
      intro: "The studio deliberately refuses to overwrite: publishing again with the same title and date says “An issue named … already exists.” That guard protects live stories — corrections go through Claude instead.",
      steps: [
        { n: 1, title: "Small typo — ask Claude", body: "In a Claude session on the website repository: “In the news issue titled X, change … to …, then commit and push.” Done in minutes." },
        { n: 2, title: "Replace a story", body: "Ask Claude to remove the original file from content/newsletters/ first, then publish the corrected version with the same title and date." },
        { n: 3, title: "Wrong date or headline", body: "Publish the corrected story fresh, then have the old one removed." },
      ],
      aside: {
        tone: "tip",
        title: "Claude in one sentence",
        body: ["Claude edits the website's master copy from plain-English requests — webinar 01 covers it, and the written chapter is at /admin/guide → “Making changes with Claude”."],
        h: 2.1,
      },
      stepsW: 7.9,
      notes: "If the audience hasn't seen webinar 01, spend a minute on what a Claude session is. The overwrite refusal surprises people — frame it as protection, not a bug.",
    },
    {
      type: "steps",
      label: "On the live site",
      title: "If Publish refuses on the live site.",
      intro: "The live hosting keeps its files read-only — a safety feature of the platform, not a fault. In a writable environment (a Claude session, or the site running locally) the same form saves instantly.",
      steps: [
        { n: 1, title: "You may see “Could not write the newsletter file”", body: "Nothing is broken and nothing was lost — the site is telling you this story needs to go through the master copy." },
        { n: 2, title: "Copy your text", body: "Title, date, summary and body — into an email to yourself or a document." },
        { n: 3, title: "Ask Claude to publish it", body: "“Publish this news story: [paste your title, date, summary and text], then commit and push.” The story appears after the automatic republish — a few minutes." },
      ],
      panel: {
        tone: "tip",
        title: "Why it works this way",
        body: "Every change to the live site goes through the version-tracked master copy — that is what makes stories traceable and recoverable. Webinar 06 explains the machinery.",
        h: 1.05,
      },
      stepsW: 8.4,
      notes: "This is the guide's “Making changes stick on live hosting” routine applied to news. The error message is the site being honest, not failing — that reframe removes the panic.",
    },
    {
      type: "steps",
      label: "Signups",
      title: "The subscribe box, and the live subscriber list.",
      intro: "The News page carries a “Subscribe” box where visitors leave their email address to hear about new issues.",
      steps: [
        { n: 1, title: "Visitors sign up on the News page", body: "Name-free and instant: they enter an email address and get a confirmation message." },
        { n: 2, title: "The admin gains a live subscriber list", body: "A subscriber section on the admin newsletter page is being rolled out as this deck is written — it shows signups as a live list you can review and use for mailings." },
        { n: 3, title: "Sending is still a manual step", body: "Publishing a story does not email anyone automatically. When an issue should reach subscribers, send it from the team mailbox to the list — until a mailing provider is wired in." },
      ],
      panel: {
        tone: "warn",
        title: "Check the rollout before relying on it",
        body: "Until the subscriber section is live in your admin, signups are not stored anywhere — treat the box as decorative and collect addresses another way.",
        h: 1.15,
      },
      stepsW: 8.4,
      notes: "Be straight with the room about the state of this feature at presentation time: open /admin/newsletter live and look for the subscriber section. If it is there, show it; if not, the warning panel applies. Update this slide once the rollout lands.",
    },
    {
      type: "steps",
      label: "Extras",
      title: "Adding a picture to a story.",
      intro: "The composer keeps to the four boxes; a story image is a one-sentence Claude request afterwards.",
      steps: [
        { n: 1, title: "Publish the story as normal", body: "Words first — the image is an addition, not a requirement. Stories without images use the house thumbnails." },
        { n: 2, title: "Ask Claude to attach the image", body: "“Add the attached photo to the news issue titled X, with alt text ‘…’, then commit and push.” Claude stores the image and links it to the story." },
        { n: 3, title: "Check the story page", body: "After the republish, the image appears on the story's own page." },
      ],
      aside: {
        tone: "tip",
        title: "Good alt text",
        body: ["One sentence describing the picture for someone who cannot see it — “Topping-out ceremony at The Courthouse, Macclesfield” — helps accessibility and search alike."],
        h: 2.0,
      },
      stepsW: 7.9,
      notes: "Underneath, Claude adds image and imageAlt lines to the story's file — the composer doesn't expose those fields, which is fine: this keeps the common path simple.",
    },
  ],
  takeaways: [
    "Four boxes, one button — and the story is live on /news immediately.",
    "Two formatting tricks: ## headings and dash bullets. Everything else is plain typing.",
    "No draft mode: agree the words before they go in the box.",
    "Corrections go through Claude — the studio refuses to overwrite live stories.",
    "On the live site, publishing goes through the repository — “Could not write” means use the Claude route.",
  ],
  help: [
    "Written walkthrough: /admin/guide → “Publishing a news story”.",
    "Formatting reminders sit right under the Body box in the studio.",
    "Story stuck or wrong? A Claude session fixes it in minutes.",
  ],
};
