// Deck 04 — The investor platform
import { C, MX, CW } from "../theme.mjs";

export const deck = {
  no: 4,
  file: "04-the-investor-platform.pptx",
  name: "The investor platform",
  title: "The investor platform.",
  subtitle: "What investors see, how to run it from the platform studio, and the routines that keep every figure current.",
  cover: "cover-investors.jpg",
  coverNotes:
    "The longest session in the series — the investor platform end to end. First what investors see, then the seven-tab studio that drives it, then the working routines: accounts, holdings, cash events, reports, insights, raises, documents and support. Take a break in the middle if you need one.",
  slides: [
    {
      type: "agenda",
      title: "What this session covers.",
      sub: "Everything an investor sees is generated from a handful of datasets you edit in one place — the platform studio.",
      items: [
        { title: "What investors see", sub: "The portal, and the two kinds of account." },
        { title: "The seven tabs", sub: "The studio's mental model in five minutes." },
        { title: "The golden rule", sub: "Portfolio values are worked out, not typed in." },
        { title: "Accounts & holdings", sub: "Create an investor, record their position, log cash." },
        { title: "Publishing to the portal", sub: "Monthly reports, insights, and upcoming raises." },
        { title: "Figures, documents & support", sub: "The quarterly routine, the data room, and the sign-in playbook." },
      ],
      notes: "Fair warning on length. If the audience only remembers two things: the golden rule (slide on values), and the quarterly routine (near the end). Everything else can be looked up in the guide chapter by chapter.",
    },
    {
      type: "imageFocus",
      label: "What investors see",
      title: "The front door: satisgroup.co.uk/investors.",
      textW: 4.3,
      image: "investor-login.png",
      caption: "The investor platform's own sign-in — black and gold, separate from the admin.",
      body: [
        { text: "Investors sign in with their email address and a password you set for them. Sessions last 24 hours; five wrong tries pauses that connection for 15 minutes — the same protections as the admin.", size: 11 },
        { text: "Not an investor yet? The “Become an investor” buttons lead to a short enquiry form at /investors/enquire — name, email, company — styled to match the platform.", size: 11 },
      ],
      panel: {
        tone: "tip",
        title: "Separate doors, separate keys",
        body: "Investor accounts are managed inside the platform studio — not on the admin accounts page. Different system entirely.",
        y: 5.45, h: 1.3,
      },
      notes: "Show the live page if connected. The enquiry form is new — it captures prospective investors in the platform's own branding and emails each submission to the enquiries inbox (covered in webinar 07).",
    },
    {
      type: "imageFocus",
      label: "What investors see",
      title: "Inside the portal: every figure traces back to you.",
      textW: 4.05,
      image: "investor-portal.png",
      caption: "An invested client's overview — portfolio value, committed capital, weighted IRR, distributions.",
      body: [
        { text: "The overview greets the investor by first name and shows their headline numbers, live raises, latest reports and a value-progression chart.", size: 11 },
        { text: "Every single figure on this screen is generated from something you edit in the platform studio — nothing on the portal is typed directly.", size: 11 },
        { text: "The sidebar navigation adapts to the kind of account — next slide.", size: 11 },
      ],
      notes: "Let the room absorb the screenshot — most of the team never sees the portal from the investor side. The framing sentence matters: the portal is a projection of the studio's data, which is why the studio routines are the whole game.",
    },
    {
      type: "panels",
      label: "What investors see",
      title: "Two kinds of account, two different portals.",
      intro: "Every account is either prospective or invested — and the platform works the type out automatically: an account holding a position counts as invested.",
      cols: 2,
      panels: [
        {
          tone: "plain", title: "Prospective — considering investing",
          body: [
            "Sees: overview, upcoming investments (deal flow), the data room, track record, market intelligence, insights.",
            "Does not see: cap tables, financials, monthly reports — construction detail stays with committed investors.",
            "The shop window: raises and research make the case.",
          ],
        },
        {
          tone: "plain", title: "Invested — money in",
          body: [
            "Sees: overview (with live raises flagged), My portfolio — a tab per investment with its files — developments, monthly reports, market intelligence, insights, financials and documents.",
            "Figures update the moment you save in the studio.",
            "Becomes the account type automatically when a position is recorded.",
          ],
        },
      ],
      panelH: 3.05,
      notes: "The automatic tier is a favourite support fact: record a cap-table position and the account upgrades itself to invested — no switch to remember. The override drop-down on the investor form exists for rare exceptions only. My portfolio is the newest section: one tab per investment, each with its own private file library.",
    },
    {
      type: "steps",
      label: "The studio",
      title: "Seven tabs run the whole platform.",
      intro: "From the control room, click Investors. Each tab edits one kind of information, and the small number on a tab shows how many records it holds.",
      image: "platform-tabs.png",
      imageW: 6.5,
      imageH: 1.1,
      stepsDy: 1.35,
      caption: "The platform studio's tab bar at /admin/platform.",
      steps: [
        { n: 1, title: "Investors", body: "Accounts and quarterly valuations." },
        { n: 2, title: "Developments & SPVs", body: "Each project and the company that owns it." },
        { n: 3, title: "Cap tables & returns", body: "Who owns what share; money in and out." },
        { n: 4, title: "Monthly reports · 5 Insights · 6 Opportunities", body: "What you publish to the portal: project updates, research, and raises." },
        { n: 7, title: "Import / export", body: "Everything as one file — backup, bulk edit, restore." },
      ],
      bodySize: 10,
      notes: "Don't teach every tab now — this is the map. SPV in plain English: the limited company set up to own one development; investors buy shares in the SPV, not the building. Cap table: the list of who owns what percentage of it.",
    },
    {
      type: "diagram",
      label: "The golden rule",
      title: "Portfolio values are worked out, not typed in.",
      intro: "You never type an investor's portfolio value anywhere. The platform computes it from two numbers you do control:",
      draw: (s, T) => {
        const y = 3.3, h = 1.2;
        T.node(s, { x: MX + 0.4, y, w: 3.0, h, label: "Share %", sub: "from the cap table" });
        s.addText("×", { x: MX + 3.55, y: y + 0.25, w: 0.6, h: 0.7, align: "center", fontFace: "Work Sans", fontSize: 30, color: C.ink, margin: 0 });
        T.node(s, { x: MX + 4.3, y, w: 3.0, h, label: "SPV equity value", sub: "from Developments & SPVs" });
        s.addText("=", { x: MX + 7.45, y: y + 0.25, w: 0.6, h: 0.7, align: "center", fontFace: "Work Sans", fontSize: 30, color: C.ink, margin: 0 });
        T.node(s, { x: MX + 8.2, y, w: 3.6, h, label: "The investor's value", sub: "computed, per holding, summed", fillDark: true });
        s.addText([
          { text: "Two things follow.  ", options: { fontSize: 11.5, bold: true, color: C.ink } },
          { text: "A revaluation is one edit — update the SPV's equity value and every holder's figures move at once. And when a portal figure looks wrong, the cause is always one of these two numbers: the share % or the equity value. Check both; the culprit is one of them.", options: { fontSize: 11.5, color: C.muted } },
        ], { x: MX, y: 5.15, w: CW - 0.8, h: 0.95, fontFace: "Work Sans", margin: 0, lineSpacing: 17 });
      },
      notes: "This is the platform's single most important idea and the diagnosis shortcut for every “my valuation looks wrong” call. Weighted IRR and distributions derive similarly — from SPV forecasts and paid cash events.",
    },
    {
      type: "steps",
      label: "Routine — accounts",
      title: "Creating an investor account.",
      intro: "Investors tab → the “Add or update investor” form. About five minutes.",
      image: "investor-form.png",
      imageW: 4.6,
      caption: "Numbers match the on-screen badges. After Save investor: a green confirmation, and the account lists as “Prospective investor”, £0, 0 positions — exactly right before any holding exists.",
      steps: [
        { n: 1, title: "Account / entity name", body: "As it should appear in their portal — e.g. “Hartwell Family Office”." },
        { n: 2, title: "Contact first name", body: "Used for greetings — “Good morning, James”." },
        { n: 3, title: "Account ID — leave empty", body: "Derived automatically. You only type one to update an existing account." },
        { n: 4, title: "Login email", body: "What they sign in with. Double-check the spelling — a typo locks them out." },
        { n: 5, title: "Account type — leave as is", body: "The platform derives it from holdings." },
        { n: 6, title: "Password — note it now", body: "Scrambled the instant you save; never visible again." },
      ],
      bodySize: 9.5,
      notes: "Emphasise noting the starting password before saving — hashed means unreadable afterwards. The account card's ID (shown as “ID …”) is how you address the account later for updates.",
    },
    {
      type: "panels",
      label: "Routine — accounts",
      title: "Handing over credentials — safely.",
      cols: 3,
      panels: [
        {
          tone: "plain", title: "Use a trusted channel",
          body: ["Ideally by phone. Or split across two channels: email address by email, password by text message."],
        },
        {
          tone: "warn", title: "Never both in one email",
          body: ["If that email is ever compromised, so is their portal. One thread must never carry the address and the password together."],
        },
        {
          tone: "plain", title: "Then encourage a prompt sign-in",
          body: ["Point them at the website's Investors page. Trouble getting in? The support playbook near the end of this session covers every common case."],
        },
      ],
      panelH: 2.35,
      notes: "Same handover discipline as admin accounts. Investors are exactly the audience attackers would impersonate — a phone call for the password is thirty seconds well spent.",
    },
    {
      type: "steps",
      label: "Routine — money",
      title: "Recording a holding (a cap-table position).",
      intro: "Cap tables & returns tab, top half. This is what turns a prospect into an invested client.",
      image: "captable-form.png",
      imageW: 4.9,
      caption: "The add-or-update position form.",
      steps: [
        { n: 1, title: "Development / SPV", body: "Which project the holding is in." },
        { n: 2, title: "Platform investor — or external holder", body: "Pick the account. Use the External holder box only for shareholders without a portal account (e.g. the Satis Group stake). One or the other, never both." },
        { n: 3, title: "Committed", body: "What they put in — £250k and £250,000 both work." },
        { n: 4, title: "Share %", body: "Their agreed percentage of the SPV — e.g. 12.5." },
        { n: 5, title: "Status", body: "Active for live; Realised or Exited for concluded holdings." },
      ],
      bodySize: 9.5,
      panel: {
        tone: "warn",
        title: "The 100% guard",
        body: "One SPV's positions can never exceed 100% — the form refuses and names the total it would have reached. Surprised? Something already on the table holds that share.",
        h: 1.1,
      },
      notes: "Check after saving: on the Investors tab the account now shows the position, a value equal to share% × equity value, and reads “Invested” automatically. Re-saving the same investor+SPV replaces the position — that's also how you correct one.",
    },
    {
      type: "steps",
      label: "Routine — money",
      title: "Logging cash events.",
      intro: "Same tab, lower half. Cash events are the money-movement history: paid events feed “distributions to date”; forecast events appear as upcoming.",
      image: "cash-event-form.png",
      imageW: 4.9,
      caption: "The record-cash-event form.",
      steps: [
        { n: 1, title: "Investor", body: "Whose money is moving." },
        { n: 2, title: "Type", body: "Distribution (profit out) · Forecast distribution (planned) · Capital call (money in) · Interest payment." },
        { n: 3, title: "Status", body: "Paid if it happened; Forecast if expected." },
        { n: 4, title: "Date and amount", body: "Year-month-day, e.g. 2026-09-30 · £125,000." },
        { n: 5, title: "Related development", body: "Optional, but linking keeps the history tidy." },
      ],
      bodySize: 9.5,
      panel: {
        tone: "tip",
        title: "When a forecast becomes real",
        body: "Record a new event with status Paid, then Remove the old forecast entry — leaving both double-counts the history.",
        h: 1.0,
      },
      notes: "Cash events don't replace like positions do: to fix a wrong event, Remove it and record it again correctly. Paid distributions and interest are what the portal sums into “distributions to date”.",
    },
    {
      type: "steps",
      label: "Routine — publishing",
      title: "Publishing a monthly report.",
      intro: "Monthly reports tab. Reports reach invested clients only, the moment you publish — prospects never see construction detail.",
      image: "report-form.png",
      imageW: 4.35,
      caption: "The publish-monthly-report form.",
      steps: [
        { n: 1, title: "Development and period", body: "Which project, and the month written out — “August 2026” is the headline investors see." },
        { n: 2, title: "Category and title", body: "One word for the kind of update — Construction, Planning, Lettings — and a one-line headline for the month." },
        { n: 3, title: "Summary", body: "A paragraph or two: progress, issues, next steps." },
        { n: 4, title: "Tasks — one per line", body: "Three parts separated by spaced dashes: Title — detail — status. E.g. “Superstructure — Frame at level three — On programme”." },
        { n: 5, title: "Report file — next slide", body: "Leave empty for now; the report publishes fine without it." },
      ],
      bodySize: 9.5,
      panel: {
        tone: "tip",
        title: "Why task lines matter",
        body: "Each line becomes its own item investors can ask about directly. Specific, honest lines generate fewer worried calls than vague ones.",
        h: 1.0,
      },
      notes: "The task syntax is the only fiddly bit: two “ — ” separators per line. If a task looks wrong in the portal, a missing separator is almost always why. To see reports as investors do, keep an in-house invested account.",
    },
    {
      type: "steps",
      label: "Routine — publishing",
      title: "Attaching the report PDF.",
      intro: "The Report file box records where the PDF lives on the website — it does not upload the file. Getting it there is a one-off step per report:",
      steps: [
        { n: 1, title: "Ask Claude to add the file", body: "In a session on the website repository: “Add this PDF as public/investor-reports/august-2026.pdf” — and attach the file. Or hand it to the development team." },
        { n: 2, title: "Type the matching path", body: "Back in the form's Report file box, starting with a slash: /investor-reports/august-2026.pdf" },
        { n: 3, title: "Or skip it entirely", body: "The report still publishes — the portal's download button stays an inactive placeholder until a file is added." },
      ],
      aside: {
        tone: "check",
        title: "In the published list",
        body: ["Each report shows its period, task count, and “report uploaded” or “no report file yet” — so missing files are visible at a glance."],
        h: 2.0,
      },
      stepsW: 7.9,
      notes: "The two-part design (file into public/investor-reports/, path in the form) is the pattern for every attached document on the platform. Same Claude request works for data-room files — two slides ahead.",
    },
    {
      type: "steps",
      label: "Routine — publishing",
      title: "Insights: research and market commentary.",
      intro: "Insights tab. Articles appear in the portal for both prospective and invested accounts — the same plain-typing style as news stories, with one extra trick.",
      image: "insight-form.png",
      imageW: 4.35,
      caption: "The compose-insight form.",
      steps: [
        { n: 1, title: "Title, category, date, read time", body: "Category is the card label — “Market note”, “Research”. Read time: about one minute per 200 words." },
        { n: 2, title: "Card colour and slug", body: "Colour is purely cosmetic — balance the page. Slug: leave empty for new articles." },
        { n: 3, title: "Summary and body", body: "Paragraphs, ## headings and - bullets as in news stories — plus pull quotes: start a line with > and a space; credit on the next line as “— Savills Research, 2026”." },
        { n: 4, title: "Publish insight", body: "Live in the portal immediately; the published list shows the article's slug." },
      ],
      bodySize: 9.5,
      panel: {
        tone: "warn",
        title: "Slugs replace — by design",
        body: "Typing an existing slug and publishing replaces that article (that is how you update one). The opposite of news stories — so keep the slug box empty for new pieces.",
        h: 1.1,
      },
      notes: "Richer blocks — statistic rows, tables, coloured callouts — exist through the JSON importer; ask Claude to add one. The slug-replace behaviour is the one asymmetry with news stories worth calling out twice.",
    },
    {
      type: "steps",
      label: "Routine — publishing",
      title: "Opportunities: advertising a raise.",
      intro: "Opportunities tab — the deal-flow page prospective investors browse, with live raises also flagged on every investor's overview. This is the shop window for prospects.",
      image: "opportunity-form.png",
      imageW: 4.35,
      caption: "The add-or-update opportunity form.",
      steps: [
        { n: 1, title: "Name, location, status", body: "Coming soon (visible, not open) · Open (accepting commitments) · Fully subscribed (closed, shown complete)." },
        { n: 2, title: "Target raise and raised to date", body: "The progress bar is worked out from these two — £3.2m target with £2.1m raised shows 66%." },
        { n: 3, title: "The headline terms", body: "Min commitment, target IRR %, target multiple, horizon, and the structure — what investors actually buy, e.g. “Ordinary shares in Satis (QUBE) Ltd”." },
        { n: 4, title: "Summary and highlights", body: "The pitch. Highlights are one per line and render as a bulleted list." },
      ],
      bodySize: 9.5,
      panel: {
        tone: "tip",
        title: "Keep the bar moving",
        body: "Update Raised to date as commitments land — a moving bar does more for momentum than any covering email. When the raise completes: status Fully subscribed, then record each position on the cap table — the moment prospects become invested.",
        h: 1.25,
      },
      notes: "Plain English for the terms: IRR = annualised return the deal aims for; multiple = money back per pound in (1.6x = £1.60 per £1). Updating uses the fill-in-everything rule: type the opportunity's ID, complete the whole form, save.",
    },
    {
      type: "steps",
      label: "Routine — figures",
      title: "The quarterly routine that keeps every portal current.",
      intro: "Investor confidence lives and dies on figures being current. Fifteen minutes at each quarter end:",
      steps: [
        { n: 1, title: "Update each SPV's equity value", body: "Developments & SPVs tab. Type the development's ID to update it — and fill in the whole form: saving replaces everything, so copy current values across first, change what changed, save. This one number moves every holder's value." },
        { n: 2, title: "Record each investor's quarterly valuation", body: "Investors tab → “Record quarterly valuation”: investor, period label (“Q3 2026”), portfolio value — normally exactly the computed value already shown on their card. Adds the point to their value-progression chart." },
        { n: 3, title: "Publish the monthly reports", body: "As covered — one per development, while the valuation numbers are fresh." },
      ],
      aside: {
        tone: "warn",
        title: "The fill-in-everything rule",
        body: ["Updating a development with only one box filled saves the other fields empty. Copy the card's current values into the form first — then edit."],
        h: 2.2,
      },
      stepsW: 7.9,
      notes: "Also update Progress %, phase/status and next-report date while in the development form — they set expectations in the portal. Do all three steps together and every portal is current at once.",
    },
    {
      type: "steps",
      label: "Routine — documents",
      title: "The data room: memorandums, appraisals, private documents.",
      intro: "Documents are the one dataset without a form — the easiest way to change them is to ask Claude. Getting the audience right matters more than anything else here:",
      steps: [
        { n: 1, title: "Decide who should see it", body: "Every prospective (and invested) investor — marketing material like a raise memorandum. Or one investor only — a private document like their subscription agreement." },
        { n: 2, title: "Ask Claude — two proven forms", body: "“Add this PDF to the investor data room for all prospective investors: title ‘QUBE Stockport — Investment Memorandum’, dated 2026-08-19.” · “Add a private data-room document for the Hartwell account only, titled ‘Subscription agreement — signed’, using this PDF.”" },
        { n: 3, title: "Verify private really means private", body: "Sign in as a different account (the in-house one) and confirm the document is NOT visible; then as the right account to confirm it is. Thirty seconds beats a confidentiality slip." },
      ],
      aside: {
        tone: "tip",
        title: "Documents without files",
        body: ["A document entry with no file still appears as a listed item — useful for “available on request” material."],
        h: 1.9,
      },
      stepsW: 7.9,
      notes: "Under the hood Claude sets the audience and stores the PDF under public/ — nothing you need to do. The verification habit in step 3 is non-negotiable for private documents.",
    },
    {
      type: "panels",
      label: "Routine — support",
      title: "The sign-in support playbook.",
      intro: "Every “I can't get in” comes down to one of these — all fixable in minutes:",
      cols: 3,
      panels: [
        {
          tone: "plain", title: "Forgotten password → set a new one",
          body: ["Investors tab → note the account's ID → type it into the form, re-enter name, first name and email exactly as shown, type a new password, save. Tell them by phone — then they sign in."],
        },
        {
          tone: "plain", title: "“Too many attempts” → 15 minutes",
          body: ["Five failures pauses their connection. Have them wait 15 minutes — and reset the password meanwhile if they're unsure of it, so the next try succeeds."],
        },
        {
          tone: "plain", title: "“It signed me out” → normal",
          body: ["Sessions last 24 hours then quietly expire — protection, not a fault. They sign in again; nothing is lost."],
        },
      ],
      panelH: 2.55,
      notes: "The blank-password rule works in your favour: leaving Password empty when updating keeps the current one — routine detail edits can never accidentally lock someone out. To see what an investor sees, keep one in-house invested and one prospective account.",
    },
    {
      type: "imageFocus",
      label: "Routine — data",
      title: "Import, export, and the backup habit.",
      textW: 4.3,
      image: "data-tab.png",
      imageH: 4.95,
      caption: "The Import / export tab — the platform's back-up door.",
      body: [
        { text: "Export current dataset downloads everything — every investor, development, cap table, report, insight and opportunity — as one file, exactly as the live site serves it.", size: 11 },
        { text: "The same tab accepts a prepared file back: Validate & import checks everything first (including the 100% cap-table rule) and only replaces the datasets present in the file.", size: 11 },
        { text: "Export before any big editing session — the file is a perfect backup and a perfect restore.", size: 11 },
      ],
      panel: {
        tone: "tip",
        title: "JSON, in plain English",
        body: "Structured text computers read reliably. You never write it by hand — Claude reads and edits it for you.",
        y: 5.5, h: 1.25,
      },
      notes: "The export is also the bridge to Claude for bulk edits: download, attach to a session, describe the changes, import — or let studio saves commit directly on the live site (webinar 06 covers the token that enables that).",
    },
  ],
  takeaways: [
    "Everything investors see is generated from datasets you edit in the seven-tab studio.",
    "The golden rule: value = share % × SPV equity value. A wrong figure is always one of those two numbers.",
    "Position saved → account becomes invested automatically and sees reports and financials.",
    "Quarterly: equity values → valuations → reports. Fifteen minutes keeps every portal current.",
    "Documents and bulk edits go through Claude; export before big sessions.",
  ],
  help: [
    "Written chapters: /admin/guide → the Investor platform group (six chapters).",
    "Start with “How the investor platform fits together” — five minutes.",
    "Figures look wrong? Check share % and equity value before anything else.",
  ],
};
